version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3300"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
